%\VignetteKeywords{Database}
%\VignetteDepends{prostateCancerBest}
%\VignettePackage{prostateCancerBest}
%\VignetteIndexEntry{prostateCancerBest}
\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

\emph{Molecular alterations in primary prostate cancer after androgen ablation therapy. }

\emph{Best CJ, Gillespie JW, Yi Y, Chandramouli GV et al. Molecular alterations in primary prostate cancer after androgen ablation therapy. Clin Cancer Res 2005 Oct 1;11(19 Pt 1):6823-34. PMID: 16203770}


In this document, I describe how the GEO data entry for the Varambally data was processed and saved into an object for analysis in Bioconductor. First of all load the relevant libraries for grabbing and manipulaing the data

<<eval=FALSE>>=
library(GEOquery)
@


Now use the `getGEO` function with the correct ID

<<eval=FALSE>>=
geoData <- getGEO("GSE2443")[[1]]
geoData
@

The phenoData contains lots of metadata from GEO that probably won't be useful for our analysis. We just take the sample name and group colums. Groups are re-ordered according to cancer progression. We re-name the feature data so that the gene symbol column doesn't contain a space character (which will cause problems later-on).

<<eval=FALSE>>=
pd  <- data.frame(ArrayID = pData(geoData)[,"geo_accession"], Sample_Group = strtrim(pData(geoData)$title,2))
pd$Sample_Group <- gsub("AI","CastrateResistant", pd$Sample_Group)
pd$Sample_Group <- gsub("AD","HormoneDependent" ,pd$Sample_Group)

pData(geoData) <- pd

best <- geoData
save(best, file="data/best.rda")
@


\end{document}